import { cva } from "class-variance-authority";

export const gridVariants = cva("grid", {
  variants: {
    cols: {
      1: "grid-cols-1",
      2: "grid-cols-2",
      3: "grid-cols-3",
      4: "grid-cols-4",
      5: "grid-cols-5",
      6: "grid-cols-6",
      7: "grid-cols-7",
      8: "grid-cols-8",
      9: "grid-cols-9",
      10: "grid-cols-10",
      11: "grid-cols-11",
      12: "grid-cols-12",
    },
    rows: {
      1: "grid-rows-1",
      2: "grid-rows-2",
      3: "grid-rows-3",
      4: "grid-rows-4",
      5: "grid-rows-5",
      6: "grid-rows-6",
      7: "grid-rows-7",
      8: "grid-rows-8",
      9: "grid-rows-9",
      10: "grid-rows-10",
      11: "grid-rows-11",
      12: "grid-rows-12",
    },
    gap: {
      none: "gap-0",
      xs: "gap-xs",
      sm: "gap-sm",
      md: "gap-md",
      lg: "gap-lg",
      xl: "gap-xl",
      "2xl": "gap-2xl",
      "3xl": "gap-3xl",
    },
    rowGap: {
      none: "row-gap-0",
      xs: "row-gap-xs",
      sm: "row-gap-sm",
      md: "row-gap-md",
      lg: "row-gap-lg",
      xl: "row-gap-xl",
      "2xl": "row-gap-2xl",
      "3xl": "row-gap-3xl",
    },
    columnGap: {
      none: "column-gap-0",
      xs: "column-gap-xs",
      sm: "column-gap-sm",
      md: "column-gap-md",
      lg: "column-gap-lg",
      xl: "column-gap-xl",
      "2xl": "column-gap-2xl",
      "3xl": "column-gap-3xl",
    },
    autoFlow: {
      row: "grid-auto-flow-row",
      column: "grid-auto-flow-col",
      dense: "grid-auto-flow-dense",
    },
    alignItems: {
      start: "items-start",
      end: "items-end",
      center: "items-center",
      stretch: "items-stretch",
    },
    justifyItems: {
      start: "justify-items-start",
      end: "justify-items-end",
      center: "justify-items-center",
      stretch: "justify-items-stretch",
    },
    alignContent: {
      start: "content-start",
      end: "content-end",
      center: "content-center",
      stretch: "content-stretch",
      between: "content-between",
      around: "content-around",
      evenly: "content-evenly",
    },
    justifyContent: {
      start: "justify-start",
      end: "justify-end",
      center: "justify-center",
      stretch: "justify-stretch",
      between: "justify-between",
      around: "justify-around",
      evenly: "justify-evenly",
    },
    autoCols: {
      min: "auto-cols-min",
      max: "auto-cols-max",
      fr: "auto-cols-fr",
      true: "auto-cols-auto",
    },
    autoRows: {
      min: "auto-rows-min",
      max: "auto-rows-max",
      fr: "auto-rows-fr",
      true: "auto-rows-auto",
    },
    templatePreset: {
      sidebar: "grid-cols-[200px_1fr]",
      hero: "grid-cols-[1fr_400px]",
      masonry: "grid-cols-[repeat(auto-fill,minmax(250px,1fr))]",
      "card-list": "grid-cols-[repeat(auto-fill,minmax(300px,1fr))]",
      symmetric: "grid-cols-[repeat(auto-fit,minmax(200px,1fr))]",
      asymmetric: "grid-cols-[200px_1fr_300px]",
    },
  },
  defaultVariants: {
    gap: "none",
    autoFlow: "row",
    alignItems: "stretch",
    justifyItems: "stretch",
    alignContent: "stretch",
    justifyContent: "start",
  },
});
