import { cva } from "class-variance-authority";

export const flexVariants = cva("transition-all duration-normal w-full", {
  variants: {
    direction: {
      row: "flex-row",
      column: "flex-col",
      "row-reverse": "flex-row-reverse",
      "column-reverse": "flex-col-reverse",
    },
    wrap: {
      nowrap: "flex-nowrap",
      wrap: "flex-wrap",
      "wrap-reverse": "flex-wrap-reverse",
    },
    justify: {
      start: "justify-start",
      end: "justify-end",
      center: "justify-center",
      between: "justify-between",
      around: "justify-around",
      evenly: "justify-evenly",
    },
    align: {
      start: "items-start",
      end: "items-end",
      center: "items-center",
      stretch: "items-stretch",
      baseline: "items-baseline",
    },
    gap: {
      none: "gap-0",
      xs: "gap-xs",
      sm: "gap-sm",
      md: "gap-md",
      lg: "gap-lg",
      xl: "gap-xl",
      "2xl": "gap-2xl",
      "3xl": "gap-3xl",
      custom: "",
    },
    padding: {
      none: "p-0",
      xs: "p-xs",
      sm: "p-sm",
      md: "p-md",
      lg: "p-lg",
      xl: "p-xl",
      "2xl": "p-2xl",
      "3xl": "p-3xl",
      custom: "",
    },
    paddingX: {
      none: "px-0",
      xs: "px-xs",
      sm: "px-sm",
      md: "px-md",
      lg: "px-lg",
      xl: "px-xl",
      "2xl": "px-2xl",
      "3xl": "px-3xl",
      custom: "",
    },
    paddingY: {
      none: "py-0",
      xs: "py-xs",
      sm: "py-sm",
      md: "py-md",
      lg: "py-lg",
      xl: "py-xl",
      "2xl": "py-2xl",
      "3xl": "py-3xl",
      custom: "",
    },
    inline: {
      true: "inline-flex",
      false: "flex",
    },
  },
  defaultVariants: {
    direction: "row",
    wrap: "nowrap",
    justify: "start",
    align: "stretch",
    gap: "none",
    padding: "none",
    inline: false,
  },
});
