import { cva } from "class-variance-authority";

export const layoutVariants = cva("", {
  variants: {
    position: {
      static: "static",
      relative: "relative",
      absolute: "absolute",
      fixed: "fixed",
      sticky: "sticky",
    },
    padding: {
      none: "p-0",
      xs: "p-xs",
      sm: "p-sm",
      md: "p-md",
      lg: "p-lg",
      xl: "p-xl",
      "2xl": "p-2xl",
      "3xl": "p-3xl",
      unset: "",
    },
    paddingX: {
      none: "px-0",
      xs: "px-xs",
      sm: "px-sm",
      md: "px-md",
      lg: "px-lg",
      xl: "px-xl",
      "2xl": "px-2xl",
      "3xl": "px-3xl",
      unset: "",
    },
    paddingY: {
      none: "py-0",
      xs: "py-xs",
      sm: "py-sm",
      md: "py-md",
      lg: "py-lg",
      xl: "py-xl",
      "2xl": "py-2xl",
      "3xl": "py-3xl",
      unset: "",
    },
    paddingTop: {
      none: "pt-0",
      xs: "pt-xs",
      sm: "pt-sm",
      md: "pt-md",
      lg: "pt-lg",
      xl: "pt-xl",
      "2xl": "pt-2xl",
      "3xl": "pt-3xl",
      unset: "",
    },
    paddingRight: {
      none: "pr-0",
      xs: "pr-xs",
      sm: "pr-sm",
      md: "pr-md",
      lg: "pr-lg",
      xl: "pr-xl",
      "2xl": "pr-2xl",
      "3xl": "pr-3xl",
      unset: "",
    },
    paddingBottom: {
      none: "pb-0",
      xs: "pb-xs",
      sm: "pb-sm",
      md: "pb-md",
      lg: "pb-lg",
      xl: "pb-xl",
      "2xl": "pb-2xl",
      "3xl": "pb-3xl",
      unset: "",
    },
    paddingLeft: {
      none: "pl-0",
      xs: "pl-xs",
      sm: "pl-sm",
      md: "pl-md",
      lg: "pl-lg",
      xl: "pl-xl",
      "2xl": "pl-2xl",
      "3xl": "pl-3xl",
      unset: "",
    },
    margin: {
      none: "m-0",
      xs: "m-xs",
      sm: "m-sm",
      md: "m-md",
      lg: "m-lg",
      xl: "m-xl",
      "2xl": "m-2xl",
      "3xl": "m-3xl",
      unset: "",
    },
    marginX: {
      none: "mx-0",
      xs: "mx-xs",
      sm: "mx-sm",
      md: "mx-md",
      lg: "mx-lg",
      xl: "mx-xl",
      "2xl": "mx-2xl",
      "3xl": "mx-3xl",
      unset: "",
    },
    marginY: {
      none: "my-0",
      xs: "my-xs",
      sm: "my-sm",
      md: "my-md",
      lg: "my-lg",
      xl: "my-xl",
      "2xl": "my-2xl",
      "3xl": "my-3xl",
      unset: "",
    },
    marginTop: {
      none: "mt-0",
      xs: "mt-xs",
      sm: "mt-sm",
      md: "mt-md",
      lg: "mt-lg",
      xl: "mt-xl",
      "2xl": "mt-2xl",
      "3xl": "mt-3xl",
      unset: "",
    },
    marginRight: {
      none: "mr-0",
      xs: "mr-xs",
      sm: "mr-sm",
      md: "mr-md",
      lg: "mr-lg",
      xl: "mr-xl",
      "2xl": "mr-2xl",
      "3xl": "mr-3xl",
      unset: "",
    },
    marginBottom: {
      none: "mb-0",
      xs: "mb-xs",
      sm: "mb-sm",
      md: "mb-md",
      lg: "mb-lg",
      xl: "mb-xl",
      "2xl": "mb-2xl",
      "3xl": "mb-3xl",
      unset: "",
    },
    marginLeft: {
      none: "ml-0",
      xs: "ml-xs",
      sm: "ml-sm",
      md: "ml-md",
      lg: "ml-lg",
      xl: "ml-xl",
      "2xl": "ml-2xl",
      "3xl": "ml-3xl",
      unset: "",
    },
    height: {
      auto: "h-auto",
      full: "h-full",
      screen: "h-screen",
      unset: "",
    },
    heightMin: {
      auto: "min-h-auto",
      full: "min-h-full",
      screen: "min-h-screen",
      unset: "",
    },
    heightMax: {
      auto: "max-h-auto",
      full: "max-h-full",
      screen: "max-h-screen",
      unset: "",
    },
    width: {
      auto: "w-auto",
      full: "w-full",
      screen: "w-screen",
      unset: "",
    },
    widthMin: {
      auto: "min-w-auto",
      full: "min-w-full",
      screen: "min-w-screen",
      unset: "",
    },
    widthMax: {
      auto: "max-w-auto",
      full: "max-w-full",
      screen: "max-w-screen",
      unset: "",
    },
    overflow: {
      visible: "overflow-visible",
      hidden: "overflow-hidden",
      auto: "overflow-auto",
      scroll: "overflow-scroll",
    },
    overflowX: {
      visible: "overflow-x-visible",
      hidden: "overflow-x-hidden",
      auto: "overflow-x-auto",
      scroll: "overflow-x-scroll",
    },
    overflowY: {
      visible: "overflow-y-visible",
      hidden: "overflow-y-hidden",
      auto: "overflow-y-auto",
      scroll: "overflow-y-scroll",
    },
  },
  defaultVariants: {
    padding: "none",
    paddingX: "unset",
    paddingY: "unset",
    paddingTop: "unset",
    paddingRight: "unset",
    paddingBottom: "unset",
    paddingLeft: "unset",
    margin: "none",
    marginX: "unset",
    marginY: "unset",
    marginTop: "unset",
    marginRight: "unset",
    marginBottom: "unset",
    marginLeft: "unset",
    height: "auto",
    heightMin: "auto",
    heightMax: "auto",
    width: "auto",
    widthMin: "auto",
    widthMax: "auto",
  },
});

export default layoutVariants;
