import { cva } from "class-variance-authority";

export const layoutVariants = cva("", {
  variants: {
    position: {
      static: "static",
      relative: "relative",
      absolute: "absolute",
      fixed: "fixed",
      sticky: "sticky",
    },
    gap: {
      none: "gap-0",
      xs: "gap-xs",
      sm: "gap-sm",
      md: "gap-md",
      lg: "gap-lg",
      xl: "gap-xl",
      "2xl": "gap-2xl",
      "3xl": "gap-3xl",
      custom: "",
    },
    padding: {
      none: "p-0",
      xs: "p-xs",
      sm: "p-sm",
      md: "p-md",
      lg: "p-lg",
      xl: "p-xl",
      "2xl": "p-2xl",
      "3xl": "p-3xl",
      custom: "",
    },
    paddingX: {
      none: "px-0",
      xs: "px-xs",
      sm: "px-sm",
      md: "px-md",
      lg: "px-lg",
      xl: "px-xl",
      "2xl": "px-2xl",
      "3xl": "px-3xl",
      custom: "",
    },
    paddingY: {
      none: "py-0",
      xs: "py-xs",
      sm: "py-sm",
      md: "py-md",
      lg: "py-lg",
      xl: "py-xl",
      "2xl": "py-2xl",
      "3xl": "py-3xl",
      custom: "",
    },
    margin: {
      none: "m-0",
      xs: "m-xs",
      sm: "m-sm",
      md: "m-md",
      lg: "m-lg",
      xl: "m-xl",
      "2xl": "m-2xl",
      "3xl": "m-3xl",
      custom: "",
    },
    marginX: {
      none: "mx-0",
      xs: "mx-xs",
      sm: "mx-sm",
      md: "mx-md",
      lg: "mx-lg",
      xl: "mx-xl",
      "2xl": "mx-2xl",
      "3xl": "mx-3xl",
      custom: "",
    },
    marginY: {
      none: "my-0",
      xs: "my-xs",
      sm: "my-sm",
      md: "my-md",
      lg: "my-lg",
      xl: "my-xl",
      "2xl": "my-2xl",
      "3xl": "my-3xl",
      custom: "",
    },
    height: {
      auto: "h-auto",
      full: "h-full",
      screen: "h-screen",
      custom: "",
    },
    width: {
      auto: "w-auto",
      full: "w-full",
      screen: "w-screen",
      custom: "",
    },
    overflow: {
      visible: "overflow-visible",
      hidden: "overflow-hidden",
      auto: "overflow-auto",
      scroll: "overflow-scroll",
    },
  },
  defaultVariants: {
    gap: "none",
    padding: "none",
    margin: "none",
  },
});

export default layoutVariants;
