name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build && pnpm generate

      - name: Create release
        id: changesets
        uses: changesets/action@v1.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commitMode: github-api
